name: release

on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [K2P, K2P-USB]
    env:
      target: ${{ matrix.target }}
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext
      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh
      - name: Start build
        run: |
          cd trunk
          fakeroot ./build_firmware_ci $target
          echo "image_path=$(cd ..; ls trunk/images/*.trx | head -n 1)" >> $GITHUB_ENV
          echo "image_name=$(cd images; ls *.trx | head -n 1)" >> $GITHUB_ENV
      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ env.image_path }}
          asset_name: ${{ env.image_name }}
          asset_content_type: application/octet-stream
